application: kaffeeshare
version: alpha2go
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms      # default value
  max_pending_latency: automatic
  max_concurrent_requests: 15
default_expiration: "10m"
inbound_services:
- mail

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "24h"

- url: /static
  static_dir: static

- url: /.*
  script: _go_app
- url: /_ah/mail/
  script: _go_app

- url: /c/clear_test
  script: _go_app
  login: admin
- url: /t/search/add_to_index
  script: _go_app
  login: admin

# Just to prevent the queries to the old RSS feed URL hitting the app
- url: /feed
  static_dir: static
  expiration: "48h"
